name: deploy

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      # ------------------------------------------------------------------------
      # Setup

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Load cached node_modules
        id: cached-node_modules-dependencies
        uses: actions/cache@v2
        with:
          path: js/node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('js/package*.json') }}

      - name: Install JS deps
        if: steps.cached-node_modules-dependencies.outputs.cache-hit != 'true'
        run: |
          make npm-install

      # ------------------------------------------------------------------------
      # Build

      - name: Build website
        run: |
          make npm-build

      # ------------------------------------------------------------------------
      # Release

      - name: Preview - Upload to Netlify
        if: github.event_name == 'pull_request'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=js/out
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Prod - Upload to Netlify
        if: (github.event_name != 'pull_request') && endsWith(github.ref, '/main')
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=js/out --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
